### ISSUE TITLE
Unable to change the role and add collaborators

### ISSUE THREAD

**Issue by louim** [mirego/accent#168]
Hey! I just updated to the latest release (v1.5.0), and I can't change the role drop down, and the invite collaborator button is still disabled 😢.

![image](https://user-images.githubusercontent.com/923718/80521325-d9a7c680-8958-11ea-8c64-06bc1af13e31.png)

Related to #162

**Comment by louim** [comment]
In fact, it seems that all (most) dropdowns and buttons are not working.

**Comment by simonprev** [comment]
Hi @louim are you sure you have the latest version? I know the 1.4.x was really broken, but I deployed 1.5.0 in our "QA" environment and everything works…

Hint: If you are running 1.5.0, there is a dark mode toggle in the footer when you hover on the left corner 😉

**Comment by louim** [comment]
Hi @simonprev, I'm indeed running the latest version, I was able to activate the Dark mode. I'm still not sure what's is going wrong, this is what gets reported to Sentry: https://sentry.io/share/issue/c97c1d02d21f4d32bf81fb1bb15680ee/, sadly the stacktrace is not really useful because it is not sourcemapped 😢.

**Comment by louim** [comment]
Not sure how helpful it is, but the previous commit I had deployed was 1f8b8d49. The dropdowns were working, but I had the #162 problem (which was my fault for deploying from master 🤣)

**Comment by simonprev** [comment]
So the buttons are all disabled or are not doing anything? Same with the dropdowns? And the error you linked in Sentry appears when you load the app? Or when you click a button/dropdown?

Could you give me access to your instance in a "demo" project (sprevost@mirego.com)? I’m not reproducing the behaviours locally or in our QA env.

**Comment by louim** [comment]
I looked a bit more into it, the stacktrace I posted happen when I click on any dropdown in the app. The dropdown stays closed. I think the button problem is a side effect of the selects not working, but that's just a guess.

Is there an easy way to invite you from the command line, since i'm not able to do it from the web interface for now? 😅

I'm also deploying from the "old school" way straight from the git repo, I haven't looked at deploying from the docker image yet. Maybe that plays a role in the error were seeing? Like different Javascript dependencies resolution maybe? I tried a bit of Googling for the error, but not much is coming up since it's the minified version of the stacktrace.

**Comment by simonprev** [comment]
Yes you can do 

```elixir
Accent.CollaboratorCreator.create(%{"email" => "sprevost@mirego.com", "role" => "admin", "project_id" => "PROJECT_ID", "assigner_id" => "YOUR_USER_ID"})
```

The only difference with the Docker install and Heroku install is that the compilation of assets is done on the "compile" hook of the buildpack. So it uses the NodeJS version of the build process. The NodeJS version used in Docker is `node:10.16-alpine`

**Comment by louim** [comment]
Gave you access. Hit me up at louismichel.couture@hooktstudios.com if if something is wrong.

**Comment by louim** [comment]
Sorry all for the trouble! It seems this was a bug where the Heroku cache got corrupted.
Forcing a cache purge with [heroku-repo](https://github.com/heroku/heroku-repo):
```
heroku plugins:install heroku-repo
heroku repo:purge_cache
```
 and a redeploy fixed the problem.
