### ISSUE TITLE
Provide an ARM variant of the Docker image

### ISSUE THREAD

**Issue by Kovah** [mirego/accent#304]
Hi there, just wanted to try Accent locally on my Mac and noticed that the Docker image has no ARM variant yet. The image is currently not able to start, seems to be an emulation issue.

Anyway, I wanted to add building of the ARM image to the CI pipeline. While all used Node and Elixir images already support ARM, I was not able to build the image locally.
```

docker buildx build --platform "linux/amd64,linux/arm64" .
```
results in the following error:
```
 > [linux/arm64 jipt-builder 5/5] RUN npm ci --no-audit --no-color &&     npm run build-production:
#0 7.108 
#0 7.108 > deasync@0.1.19 install /opt/build/node_modules/deasync
#0 7.108 > node ./build.js
#0 7.108 
#0 7.293 gyp info it worked if it ends with ok
#0 7.297 gyp info using node-gyp@3.8.0
#0 7.298 gyp info using node@10.16.3 | linux | arm64
#0 7.312 gyp ERR! configure error 
#0 7.313 gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
#0 7.313 gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
#0 7.313 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
#0 7.313 gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
#0 7.313 gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
#0 7.313 gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
#0 7.313 gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
#0 7.313 gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
#0 7.313 gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
#0 7.313 gyp ERR! System Linux 5.10.104-linuxkit
#0 7.313 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#0 7.313 gyp ERR! cwd /opt/build/node_modules/deasync
#0 7.313 gyp ERR! node -v v10.16.3
#0 7.313 gyp ERR! node-gyp -v v3.8.0
#0 7.313 gyp ERR! not ok 

```

If you know what the cause for this issue is and if you are able to fix it, multi-platform builds of the Docker image can be achieved by adding `platforms: linux/amd64,linux/arm64` to the `docker/build-push-action@v1` build step like so:

```
      - uses: docker/build-push-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mirego/accent
          tag_with_ref: true
          platforms: linux/amd64,linux/arm64
          push: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master' }}
```

**Comment by whalemare** [comment]
Hello, devs. Do you have plans to add M1 support?

**Comment by simonprev** [comment]
Yes! I recently got my hands on an M1 and fixed the hard dependencies on some package that were not supported by arm64.

I have not tested yet with docker but the app will be able to run (using mix) in the next version I will release.

**Comment by simonprev** [comment]
v.1.13.0 has been developed on a MacBook M1. The Rails YAML formatter is removed when built with arm64 but everything should work now.

**Comment by Kovah** [comment]
Awesome!

**Comment by flavienbesseau** [comment]
Hello Simon,
DId you have the chance to fix the problem? From my side i still have the problem: 
<img width="1113" alt="image" src="https://github.com/mirego/accent/assets/64224833/9eafefc4-2c89-460c-b482-efdc3c7acf10">

**Comment by flavienbesseau** [comment]
Hey @simonprev 
DId you have the chance to fix the problem? From my side i still have the problem:
<img width="1113" alt="image" src="https://github.com/mirego/accent/assets/64224833/23e0d483-1666-4ed2-9b7c-f1ce3d85c077">

**Comment by david-trujillo** [comment]
> Hey @simonprev DId you have the chance to fix the problem? From my side i still have the problem: <img alt="image" width="1113" src="https://user-images.githubusercontent.com/64224833/265380886-23e0d483-1666-4ed2-9b7c-f1ce3d85c077.png">

I was able to make it work with `docker compose up` on a M2 by modifying the docker-compose.yml to:

`````
version: '3.7'
services:
  application:
    container_name: accent
    build: .
    ports:
      - 4000:4000
    depends_on:
      - postgresql
    env_file:
      - .env
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://postgres@postgresql:5432/accent_development
  postgresql:
    image: postgres:10.3
    container_name: accent-postgres
    environment:
      - POSTGRES_DB=accent_development
    ports:
      - 5432:5432
    volumes:
      - accent_psql:/var/lib/postgresql/data
volumes:
  accent_psql:
````

**Comment by rwojsznis** [comment]
> DId you have the chance to fix the problem? From my side i still have the problem: 

Seems like [official docker image](https://hub.docker.com/r/mirego/accent/tags) doesn't build for arm64 arch but you can very easily build your version with already provided `Dockerfile` 

It would be indeed nice to have official arm64 image as well on dockerhub, AFAIK gh should now nicely build multiarch images; might try to contribute myself as I'm really digging the project so far! 🤘
