### ISSUE TITLE
Translator and Proofreader

### ISSUE THREAD

**Issue by RappyTV** [mirego/accent#393]
I would appreciate a feature where "Translator" and "Proofreader" are two seperate roles so when a normal translator changes a string, it's not deployed directly and has to first be approved by a Proofreader.

**Comment by simonprev** [comment]
Just pushed a new role "translator" and a new state "translated" on a strings that is made true when the translation is saved in the UI

**Comment by RappyTV** [comment]
@simonprev I really appreciate the effort but the "Reviews tab" is just gone after the update and I don't think it's supposed this way.
As an admin: https://media.rappytv.com/u/opera_1Y3y5Q9N0T.png
As a translator & as a reviewer: https://media.rappytv.com/u/firefox_DfuMEUmsyb.png

**Comment by simonprev** [comment]
Oh yeah sorry, it was a bug in v1.19.8 but it’s fixed in v1.19.9 😄

**Comment by RappyTV** [comment]
tyvm ❤️

**Comment by RappyTV** [comment]
Translators and reviewers still don't have access to the "Review tab". Admins do

**Comment by simonprev** [comment]
Oh you’re right, fixed in https://github.com/mirego/accent/commit/6b9f7c30f67067595d4323bbc67517416305c595 and building right now in `v1.19.20`

**Comment by RappyTV** [comment]
W
